<?php

/*
 * This file is part of the ConstructBundle.
 *
 * Copyright (c) 2016 BlueMesa LabDB Contributors <labdb@bluemesa.eu>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Bluemesa\Bundle\ConstructBundle\Form;

use Bluemesa\Bundle\ConstructBundle\Entity\Construct;
use Bluemesa\Bundle\ConstructBundle\Entity\ConstructTag;
use Bluemesa\Bundle\ConstructBundle\Entity\Gateway;
use Bluemesa\Bundle\ConstructBundle\Entity\RestrictionLigation;
use Bluemesa\Bundle\ConstructBundle\Entity\TopoTa;
use Bluemesa\Bundle\ConstructBundle\Form\Type\TagsType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

/**
 * ConstructType class
 *
 * @author Radoslaw Kamil Ejsmont <radoslaw@ejsmont.net>
 */
class ConstructType extends AbstractType
{
    /**
     * @var array
     */
    private static $methods = array(
        'Restriction-Ligation' => array(
            'entity' => RestrictionLigation::class,
            'form' => RestrictionLigationType::class
        ),
        'Gateway' => array(
            'entity' => Gateway::class,
            'form' => GatewayType::class
        ),
        'TOPO/TA cloning' => array(
            'entity' => TopoTa::class,
            'form' => TopoTaType::class
        )
    );

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('id', NumberType::class, array(
                        'label'     => 'Label',
                        'required' => false,
                        'attr' => array('placeholder' => 'Leave empty for autogenerated ID')))
                ->add('name', TextType::class, array(
                        'label'     => 'Name'))
                ->add('type', ChoiceType::class, array(
                        'label' => 'Type',
                        'required'  => true,
                        'choices' => Construct::$types
                        ))
                ->add('resistances', ChoiceType::class, array(
                        'label' => 'Resistances',
                        'required'  => false,
                        'multiple' => true,
                        'choices' => Construct::$antibiotics))
                ->add('size', NumberType::class, array(
                        'label'     => 'Size',
                        'attr'      => array('class' => 'input-small'),
                        'widget_addon_append' => array(
                                'text' => 'kb',
                        )))
                ->add('sequenceFile', VichFileType::class, array(
                        'label' => 'Sequence file',
                        'required' => false))
                ->add('notes', TextareaType::class, array(
                        'label' => 'Notes',
                        'required' => false))
                ->add('tags', TagsType::class, array(
                        'label' => 'Tags',
                        'required' => false,
                        'multiple' => true,
                        'class' => ConstructTag::class,
                        'attr' => array('class' => 'tags')))
                ->add('vendor', TextType::class, array(
                        'label' => 'Vendor',
                        'required' => false))
                ->add('infoURL', UrlType::class, array(
                        'label' => 'Info URL',
                        'required' => false,
                        'attr' => array('placeholder' => 'Paste address here')))
                ->addEventListener(
                    FormEvents::PRE_SET_DATA,
                    array($this, 'onPreSetData'))
                ->addEventListener(
                    FormEvents::PRE_SUBMIT,
                    array($this, 'onPreSubmit'));
    }

    public function onPreSetData(FormEvent $event)
    {
        /** @var Construct $construct */
        $construct = $event->getData();
        $form = $event->getForm();

        if (null === $construct->getMethod()) {
            $form->add('cloningMethod', ChoiceType::class, array(
                        'label' => 'Cloning method',
                        'placeholder' => 'Select cloning method',
                        'required'  => false,
                        'mapped' => false,
                        'choices' => $this->getMethodsJSON()
            ));
        } else {
            $formType = $this->getFormTypeForMethod(get_class($construct->getMethod()));
            $form->add('method', $formType, array(
                'horizontal_label_offset_class' => null,
                'horizontal_input_wrapper_class' => 'construct_method_placeholder',
                'label_render'      => false,
                'widget_form_group' => false
            ));
        }
    }

    public function onPreSubmit(FormEvent $event)
    {
        $data = $event->getData();
        $form = $event->getForm();

        if (isset($data['cloningMethod']) && (! empty($data['cloningMethod']))) {
            $json = json_decode($data['cloningMethod'], true);
            $form->add('method', $json['form'], array(
                'horizontal_label_offset_class' => null,
                'horizontal_input_wrapper_class' => 'construct_method_placeholder',
                'label_render'      => false,
                'widget_form_group' => false
            ));
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Construct::class,
        ));
    }

    /**
     * @return array
     */
    private function getMethodsJSON()
    {
        $result = array();
        foreach (self::$methods as $name => $values) {
            $result[$name] = json_encode($values);
        }

        return $result;
    }

    /**
     * @var    string $method
     * @return string | null
     */
    private function getFormTypeForMethod($method)
    {
        foreach (self::$methods as $name => $values) {
            if ($values['entity'] == $method) {

                return $values['form'];
            }
        }

        return null;
    }
}
